//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracPersonel
    {
        public int IslemID { get; set; }
        public int AracID { get; set; }
        public int PersonelID { get; set; }
        public Nullable<System.DateTime> AldigiTarih { get; set; }
        public Nullable<System.DateTime> BiraktigiTarih { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
