//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracModel
    {
        public AracModel()
        {
            this.Araclar = new HashSet<Araclar>();
        }
    
        public int ModelID { get; set; }
        public string Model { get; set; }
        public int MarkaID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<Araclar> Araclar { get; set; }
        public virtual AracMarka AracMarka { get; set; }
    }
}
