//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracMarka
    {
        public AracMarka()
        {
            this.AracModel = new HashSet<AracModel>();
        }
    
        public int MarkaID { get; set; }
        public string Marka { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<AracModel> AracModel { get; set; }
    }
}
