//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public Bolum()
        {
            this.PersonelEgitim = new HashSet<PersonelEgitim>();
        }
    
        public int BolumID { get; set; }
        public Nullable<int> FakulteID { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Fakulte Fakulte { get; set; }
        public virtual ICollection<PersonelEgitim> PersonelEgitim { get; set; }
    }
}
