//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmanIslem
    {
        public int DerpartmanID { get; set; }
        public int BirimID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Birim_T Birim_T { get; set; }
        public virtual Departman_T Departman_T { get; set; }
    }
}
