//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilce_T
    {
        public Ilce_T()
        {
            this.Semt_T = new HashSet<Semt_T>();
        }
    
        public int ID { get; set; }
        public string IlceAdi { get; set; }
        public int SehirID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Sehir_T Sehir_T { get; set; }
        public virtual ICollection<Semt_T> Semt_T { get; set; }
    }
}
