//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinTur
    {
        public IzinTur()
        {
            this.PersonelIzin = new HashSet<PersonelIzin>();
        }
    
        public int IzinTurID { get; set; }
        public string IzinTuru { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<PersonelIzin> PersonelIzin { get; set; }
    }
}
