//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaasIslem
    {
        public int IslemID { get; set; }
        public int PersonelID { get; set; }
        public int MaasID { get; set; }
        public Nullable<System.DateTime> MaasTarihi { get; set; }
    
        public virtual Maas_T Maas_T { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
