//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okul
    {
        public Okul()
        {
            this.Fakulte = new HashSet<Fakulte>();
        }
    
        public int OkulID { get; set; }
        public string OkulAdi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<Fakulte> Fakulte { get; set; }
    }
}
