//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelIzin
    {
        public int PersonelIzinID { get; set; }
        public int IzinTurID { get; set; }
        public int PersonelID { get; set; }
        public Nullable<System.DateTime> IzinBasTarihi { get; set; }
        public Nullable<System.DateTime> IzinBitisTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual IzinTur IzinTur { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
