//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.AracPersonel = new HashSet<AracPersonel>();
            this.BirimIslem = new HashSet<BirimIslem>();
            this.Kullanici = new HashSet<Kullanici>();
            this.MaasIslem = new HashSet<MaasIslem>();
            this.PersonelEgitim = new HashSet<PersonelEgitim>();
            this.PersonelGirisCikis = new HashSet<PersonelGirisCikis>();
            this.PersonelIletisim = new HashSet<PersonelIletisim>();
            this.PersonelIzin = new HashSet<PersonelIzin>();
            this.PrimIslem = new HashSet<PrimIslem>();
            this.UnvanIslem = new HashSet<UnvanIslem>();
            this.YetkiIslem = new HashSet<YetkiIslem>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string TCNo { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<AracPersonel> AracPersonel { get; set; }
        public virtual ICollection<BirimIslem> BirimIslem { get; set; }
        public virtual ICollection<Kullanici> Kullanici { get; set; }
        public virtual ICollection<MaasIslem> MaasIslem { get; set; }
        public virtual ICollection<PersonelEgitim> PersonelEgitim { get; set; }
        public virtual ICollection<PersonelGirisCikis> PersonelGirisCikis { get; set; }
        public virtual ICollection<PersonelIletisim> PersonelIletisim { get; set; }
        public virtual ICollection<PersonelIzin> PersonelIzin { get; set; }
        public virtual ICollection<PrimIslem> PrimIslem { get; set; }
        public virtual ICollection<UnvanIslem> UnvanIslem { get; set; }
        public virtual ICollection<YetkiIslem> YetkiIslem { get; set; }
    }
}
