//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelIletisim
    {
        public int ID { get; set; }
        public int PersonelID { get; set; }
        public string CepTel { get; set; }
        public string EvTel { get; set; }
        public string EMail { get; set; }
        public Nullable<int> SemtID { get; set; }
        public string AcikAdres { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Semt_T Semt_T { get; set; }
    }
}
