//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimCesidi
    {
        public PrimCesidi()
        {
            this.PrimIslem = new HashSet<PrimIslem>();
        }
    
        public int PrimID { get; set; }
        public string PrimCesidi1 { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<PrimIslem> PrimIslem { get; set; }
    }
}
