//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unvan
    {
        public Unvan()
        {
            this.UnvanIslem = new HashSet<UnvanIslem>();
        }
    
        public int ID { get; set; }
        public string UnvanAdi { get; set; }
    
        public virtual ICollection<UnvanIslem> UnvanIslem { get; set; }
    }
}
