//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki_T
    {
        public Yetki_T()
        {
            this.YetkiIslem = new HashSet<YetkiIslem>();
        }
    
        public int YetkiID { get; set; }
        public string YetkiAdi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<YetkiIslem> YetkiIslem { get; set; }
    }
}
